lcgcmt_installarea=without_installarea
CMTPATH=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
CMT_tag=$(tag)
CMTROOT=/afs/ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/CMT/v1r25
CMT_root=/afs/ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/CMT/v1r25
CMTVERSION=v1r25
CMT_offset=/afs/ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/share/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/share/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/InstallArea/share/bin:/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/x86_64-slc6-gcc46-opt/scripts:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/scripts:/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/${CMTCONFIG}/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/${CMTCONFIG}/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/xrootd/3.2.7/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/Python/2.7.3/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/gcc/4.6.3/x86_64-slc6/bin:/afs/ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/CMT/v1r25/${CMTBIN}:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/sqlite/3070900/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/XercesC/3.1.1p1/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/mysql/5.5.14/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/gcc/4.6.3/x86_64-slc6/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/bin:/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/java/latest/bin:/opt/puppetlabs/bin:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/cernlib/2006a/x86_64-slc6-gcc46-opt/bin:/afs/.ihep.ac.cn/bes3/offline/sw/contrib/DAWN/3.85/bin/Linux:/afs/.ihep.ac.cn/bes3/offline/sw/contrib/DAWN/3.85/../bin/Linux:/afs/.ihep.ac.cn/bes3/offline/sw/contrib/DAVID/1.34/bin/Linux
CLASSPATH=/afs/ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/CMT/v1r25/java
debug_option=-g
cc=$(cc_name)
cdebugflags=$(coptimized_s)
cflags= -fmessage-length=0 -fPIC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
cdepflags=-MMD -MP -MF $*.d -MQ $@
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0    -Wall -Wextra  -pthread  -Wno-deprecated -D_GNU_SOURCE -pthread -pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long  -fPIC -march=x86-64 -mtune=x86-64 -pedantic-errors -O2
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT  -DBOOST_FILESYSTEM_VERSION=3 
cppcomp=$(cpp) -c $(cppdebugflags) $(cppflags) $(pp_cppflags) $(includes)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl  -Wl,--no-undefined -Wl,--export-dynamic 
cpplink=$(cpp) $(cpplinkflags)
cppdepflags=-MMD -MP -MF $*.d -MQ $@
for=$(for_name)
fflags=-fmessage-length=0 -O2   -fPIC -pipe -fno-second-underscore -Wall -W -Wsurprising -fPIC 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=symlink.sh
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl69-gcc463
HltTools_tag=$(tag)
HLTTOOLSROOT=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/EventFilter/HltUtilities/HltTools/HltTools-01-00-02
HltTools_root=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/EventFilter/HltUtilities/HltTools/HltTools-01-00-02
HLTTOOLSVERSION=HltTools-01-00-02
HltTools_cmtpath=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5
HltTools_offset=EventFilter/HltUtilities
HltTools_project=BOSS
HltTools_project_release=7.0.5
BesPolicy_tag=$(tag)
BESPOLICYROOT=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesPolicy/BesPolicy-01-05-05
BesPolicy_root=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesPolicy/BesPolicy-01-05-05
BESPOLICYVERSION=BesPolicy-01-05-05
BesPolicy_cmtpath=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5
BesPolicy_project=BOSS
BesPolicy_project_release=7.0.5
BesCxxPolicy_tag=$(tag)
BESCXXPOLICYROOT=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesCxxPolicy/BesCxxPolicy-00-01-01
BesCxxPolicy_root=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesCxxPolicy/BesCxxPolicy-00-01-01
BESCXXPOLICYVERSION=BesCxxPolicy-00-01-01
BesCxxPolicy_cmtpath=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5
BesCxxPolicy_project=BOSS
BesCxxPolicy_project_release=7.0.5
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiPolicy
GaudiPolicy_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiPolicy
GAUDIPOLICYVERSION=v12r7
GaudiPolicy_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v23r9
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Settings
LCG_Settings_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_65a
LCG_releases=${EXTERNALLIBDIR}/external
LCG_external=${EXTERNALLIBDIR}/external
unixdirname=lib64
gcc_config_version=4.6.3
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
clang_native_version=$(clang_config_version)
clang_home=$(LCG_external)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp_name)
for_name=lcg-gfortran-$(gcc_config_version)
COMPILER_PATH=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/gcc/4.6.3/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.6.3
LD_LIBRARY_PATH=/lib:/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/${CMTCONFIG}/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/${CMTCONFIG}/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/clhep/2.0.4.5/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/Boost/1.50.0_python2.7/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/xrootd/3.2.7/x86_64-slc6-gcc46-opt/lib64:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/libunwind/5c2cade/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/gcc/4.6.3/x86_64-slc6/lib64:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/XercesC/3.1.1p1/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/mysql/5.5.14/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/HepPDT/2.06.01/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/HepMC/2.06.08/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/lib64:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/lapack/3.4.0/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/blas/20110419/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/CppUnit/1.12.1_p1/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/gcc/4.6.3/x86_64-slc6/lib64:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/contrib/gcc/4.6.3/x86_64-slc6/lib:/usr/lib64:/usr/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/BesGDML/2.8.0/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/DIM/dim_v19r11/x86_64-slc6-gcc46-opt/linux:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/geant4/4.9.3p01/x86_64-slc6-gcc46-opt/lib/Linux-g++:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/xmlrpc-c/xmlrpc-c-1.25.27/x86_64-slc6-gcc46-opt/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/genbes/genbes-00-00-11/x86_64-slc6-gcc46-opt:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/LessTif/Motif1.2/lib:/usr/local/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/sqlite/3.6.11/slc4_ia32_gcc34/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/Python/2.7.3/x86_64-slc6-gcc46-opt/lib
Python_tag=$(tag)
PYTHONROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/Python
Python_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_65a
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Configuration
LCG_Configuration_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_65a
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Platforms
LCG_Platforms_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_65a
LCG_arch=x86_64
LCG_os=slc6
LCG_compiler=gcc46
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-opt
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_compiler=UnknownCompiler
host_arch=x86_64
host_os=linux
host_cmtconfig=x86_64-linux-UnknownCompiler-opt
LCG_hostos=$(host_arch)-$(LCG_os)
LCG_hostarch=$(host_arch)
LCG_config_version=65a
COOL_config_version=COOL_2_8_18a
CORAL_config_version=CORAL_2_3_27a
RELAX_config_version=RELAX_1_3_0m
ROOT_config_version=5.34.09
AIDA_config_version=3.2.1
4suite_config_version=1.0.2p1
bjam_config_version=3.1.13
blas_config_version=20110419
Boost_config_version=1.50.0
Boost_file_version=1_50
CASTOR_config_version=2.1.13-6
cernlib_config_version=2006a
cgsigsoap_config_version=1.3.3-1
CLHEP_config_version=2.0.4.5
cmake_config_version=2.8.9
cmt_config_version=v1r20p20081118
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
CppUnit_config_version=1.12.1_p1
cx_oracle_config_version=5.1.1
david_config_version=1_36a
dawn_config_version=3_88a
dcache_client_config_version=2.47.6-1
dcache_srm_config_version=1.9.5-23
dcap_config_version=2.47.6
doxygen_config_version=1.8.2
dpm_config_version=1.8.5-1
epel_config_version=20120618
Expat_config_version=2.0.1
fftw_config_version=3.1.2
Frontier_Client_config_version=2.8.5p1
fastjet_config_version=3.0.3
GCCXML_config_version=0.9.0_20120309p2
gdb_config_version=7.6
genshi_config_version=0.6
gfal_config_version=1.13.0-0
globus_config_version=4.0.7-VDT-1.10.1
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.1.4-2
GSL_config_version=1.10
HepMC_config_version=2.06.08
HepPDT_config_version=2.06.01
igprof_config_version=5.9.6
ipython_config_version=0.12.1
is_ifce_config_version=1.13.0-0
javasdk_config_version=1.6.0
javajni_config_version=$(javasdk_config_version)
json_config_version=2.5.2
kcachegrind_config_version=0.4.6
lapack_config_version=3.4.0
lcgdmcommon_config_version=1.8.5-1
lcginfosites_config_version=2.6.2-1
lcgutils_config_version=1.13.0-0
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=2.4.2
libunwind_config_version=5c2cade
lxml_config_version=2.3
matplotlib_config_version=1.1.0
minuit_config_version=5.27.02
mock_config_version=0.8.0
multiprocessing_config_version=2.6.2.1
myproxy_config_version=4.2-VDT-1.10.1
mysql_config_version=5.5.14
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
nose_config_version=1.1.2
numpy_config_version=1.6.1
oracle_config_version=11.2.0.3.0
processing_config_version=0.52
py_config_version=1.4.8
py2neo_config_version=1.4.6
pydot_config_version=1.0.28
pyanalysis_config_version=1.3
pygraphics_config_version=1.4
pygsi_config_version=0.5
pylint_config_version=0.26.0
pyminuit_config_version=0.0.1
pytest_config_version=2.2.4
pytools_config_version=1.8
Python_config_version=2.7.3
Python_config_version_twodigit=2.7
pyqt_config_version=4.9.5
pyparsing_config_version=1.5.6
pyxml_config_version=0.8.4p1
QMtest_config_version=2.4.1
qt_config_version=4.8.4
qwt_config_version=6.0.1
readline_config_version=2.5.1p1
roofit_config_version=3.10p1
setuptools_config_version=0.6c11
scipy_config_version=0.10.0
sip_config_version=4.14
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3070900
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
sympy_config_version=0.7.1
tbb_config_version=41_20121003
tcmalloc_config_version=1.7p3
uuid_config_version=1.42
valgrind_config_version=3.8.0
vdt_config_version=0.3.2
voms_config_version=2.0.8-1
vomsapic_config_version=1.9.17-1
vomsapicpp_config_version=1.9.17-1
vomsapi_noglobus_config_version=1.9.17-1
vomsclients_config_version=1.9.17-1
XercesC_config_version=3.1.1p1
xqilla_config_version=2.2.4p1
xrootd_config_version=3.2.7
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/share/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/libunwind/5c2cade/x86_64-slc6-gcc46-opt/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/Python/2.7.3/x86_64-slc6-gcc46-opt/share/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/mysql/5.5.14/x86_64-slc6-gcc46-opt/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/CppUnit/1.12.1_p1/x86_64-slc6-gcc46-opt/share/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc46-opt/share/man:/opt/glite/share/man:/usr/man:/usr/share/man:/opt/puppetlabs/puppet/share/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/cernlib/2006a/x86_64-slc6-gcc46-opt/src/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/share/man:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/src/root/man
tcmalloc_tag=$(tag)
TCMALLOCROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/tcmalloc
tcmalloc_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_65a
libunwind_tag=$(tag)
LIBUNWINDROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/libunwind
libunwind_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_65a
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86_64
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python/lib-dynload
cmt_actions_constituents=       
cmt_actions_constituentsclean= new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
lib_no_static_fragment=library_no_static
cppdebugflags_s=-g
cppoptimized_s=-O2 -DNDEBUG
cppprofiled_s=-pg
cdebugflags_s=-g
coptimized_s=-O2 -DNDEBUG
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2 -DNDEBUG
fprofiled_s=-pg
GaudiKernel_linkopts= -lGaudiKernel 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl  -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000  
libraryshr_linkopts=-fPIC -ldl  -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000 
application_linkopts=-Wl,--export-dynamic 
shared_install_subdir=/$(tag)
genconfDir=$(shared_install_subdir)/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiCoreSvc=GaudiCoreSvc * -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
COOLVERS=COOL_2_8_18a
CORALVERS=CORAL_2_3_27a
ROOTVERS=5.34.09
BoostVERS=1.50.0
uuidVERS=1.42
GCCXMLVERS=0.9.0_20120309p2
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.7.3
HepMCVERS=2.06.08
QMtestVERS=2.4.1
LCGCMTVERS=65a
GAUDI_DOXY_HOME=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiRelease/doc
config_command=cp 
BesCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS '-DPACKAGE_VERSION=$(q2)$(version)$(q2)' 
q2="
BesFortranPolicy_tag=$(tag)
BESFORTRANPOLICYROOT=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesFortranPolicy/BesFortranPolicy-00-01-03
BesFortranPolicy_root=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesFortranPolicy/BesFortranPolicy-00-01-03
BESFORTRANPOLICYVERSION=BesFortranPolicy-00-01-03
BesFortranPolicy_cmtpath=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5
BesFortranPolicy_project=BOSS
BesFortranPolicy_project_release=7.0.5
f77_linkopts=-lgfortran -lnsl -lcrypt -ldl
f90_home=$(f90_home_linux)
for90=$(for90_linux)
f90pp=$(f90pp_linux)
f90flags=$(f90flags_linux)
f90ppflags=$(f90ppflags_linux)
f90comp=$(f90comp_linux)
f90link=$(f90link_linux)
f90_linkopts=$(f90_linkopts_linux)
BesFortranPolicy_linkopts=$(f77_linkopts)
BesFortranPolicy_export_paths=$(PGI_libset)
BesPolicy_scripts= -s=$(BESPOLICYROOT)/share -s=$(BESPOLICYROOT)/src symlink.sh inverse_symlink.sh get_files 
symlink_command=symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R
MAKEFLAGS= --no-print-directory 
remote_launcher=ssh -f 
application_fragment=application
library_fragment=library
library_no_share_fragment=library_no_share
install_include_filter=*.h
GaudiInterface_tag=$(tag)
GAUDIINTERFACEROOT=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/External/GaudiInterface/GaudiInterface-01-03-07
GaudiInterface_root=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/External/GaudiInterface/GaudiInterface-01-03-07
GAUDIINTERFACEVERSION=GaudiInterface-01-03-07
GaudiInterface_cmtpath=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5
GaudiInterface_offset=External
GaudiInterface_project=BOSS
GaudiInterface_project_release=7.0.5
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiKernel
GaudiKernel_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiKernel
GAUDIKERNELVERSION=v28r8
GaudiKernel_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v23r9
Reflex_tag=$(tag)
REFLEXROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/Reflex
Reflex_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_65a
ROOT_tag=$(tag)
ROOTROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/ROOT
ROOT_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_65a
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/GCCXML
GCCXML_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_65a
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
xrootd_tag=$(tag)
XROOTDROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/xrootd
xrootd_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/xrootd
XROOTDVERSION=v1
xrootd_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
xrootd_offset=LCG_Interfaces
xrootd_project=LCGCMT
xrootd_project_release=LCGCMT_65a
xrootd_native_version=$(xrootd_config_version)
xrootd_home=$(LCG_external)/xrootd/$(xrootd_native_version)/$(LCG_system)
xrootd_linkopts=-L$(xrootd_home)/$(unixdirname) 
xrootd_export_paths= $(xrootd_home)/bin $(xrootd_home)/include $(xrootd_home)/$(unixdirname)   $(xrootd_home)/share
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread  -lRIO
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/x86_64-slc6-gcc46-opt/python/lib-dynload:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/python/lib-dynload:/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/x86_64-slc6-gcc46-opt/python.zip:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/python.zip:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/lib:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/lib/python2.7/site-packages:/usr/lib64/python
rootcint="$(ROOT_home)/bin/rootcint"
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
Boost_tag=$(tag)
BOOSTROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/Boost
Boost_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_65a
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_compiler_version=$(LCG_compiler)
Boost_linkopts=-L$(Boost_home)/lib  $(Boost_linkopts_system) $(Boost_linkopts_filesystem) $(Boost_linkopts_thread) 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
includes= $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/EventFilter/HltUtilities/HltTools/HltTools-01-00-02" $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/include/HltTools" $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/x86_64-slc6-gcc46-opt/include" $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/include" $(use_includes)
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
zip_GaudiKernel_python_modules_dependencies= GaudiKernel_python_init 
GaudiKernel_python_init_dependencies= GaudiKernel_python 
GaudiKernelDict_use_linkopts=$(use_linkopts)
GaudiKernelGen_dependencies=install_more_includes
genconfig_cmd=genconf.exe
GaudiSvc_tag=$(tag)
GAUDISVCROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiSvc
GaudiSvc_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/GaudiSvc
GAUDISVCVERSION=v19r4
GaudiSvc_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9
GaudiSvc_project=GAUDI
GaudiSvc_project_release=GAUDI_v23r9
CLHEP_tag=$(tag)
CLHEPROOT=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/CLHEP
CLHEP_root=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_65a
CLHEP_native_version=$(CLHEP_config_version)
CLHEP_home=$(LCG_external)/clhep/$(CLHEP_native_version)/$(LCG_system)
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)  
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
GaudiSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
GaudiSvcstamps= $(bin)/GaudiSvcsetup.make  $(bin)/GaudiSvcsetup.make 
HltTools_linkopts= -L$(bin) -lHltTools  
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
BesCxxPolicyDir=${BESCXXPOLICYROOT}/${BINDIR}
BesPolicyDir=${BESPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
GaudiSvcDir=${GAUDISVCROOT}/${BINDIR}
GaudiInterfaceDir=${GAUDIINTERFACEROOT}/${BINDIR}
HltToolsDir=${HLTTOOLSROOT}/${BINDIR}
old_dir=`echo $(HltTools_project)/$(HltTools_project_release) | sed -e 's#//#/#g'`
old_base=`echo $(HltTools_cmtpath) | sed -e 's#/$(old_dir)##'`
sedcmd='s#$(old_base)##' -e 's#^/##' -e 's#/$##' -e 's#[^/]*#..#g'
new_base=`/bin/pwd | sed -e ${sedcmd}`
new_fincludes=`( echo $(includes) | sed -e 's#$(old_base)#$(new_base)#g')`
fincludes=`cmt show macro_value new_fincludes`
tag=x86_64-slc6-gcc46-opt
package=HltTools
version=HltTools-01-00-02
PACKAGE_ROOT=$(HLTTOOLSROOT)
srcdir=../src
bin=../$(HltTools_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/EventFilter/HltUtilities/HltTools/HltTools-01-00-02/x86_64-slc6-gcc46-opt/
project=BOSS
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(BOSS_installarea_prefix)/$(CMTCONFIG)/lib $(BOSS_installarea_prefix)/share/lib $(BOSS_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(HltTools_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
BOSS_installarea_prefix=$(cmt_installarea_prefix)
BOSS_installarea_prefix_remove=$(BOSS_installarea_prefix)
cmt_installarea_linkopts= -L/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/$(BOSS_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
GAUDI_home=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9
BOSS_home=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5
BOSS_install_include= /afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/$(BOSS_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_include= /afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_python=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python.zip
BOSS_install_python=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/$(BOSS_installarea_prefix)$(shared_install_subdir)/python.zip
GAUDI_install_pyd_module=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
BOSS_install_pyd_module=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/$(BOSS_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
GAUDI_install_scripts=/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
BOSS_install_scripts=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/$(BOSS_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=$(CMTINSTALLAREA)$(shared_install_subdir)/python
JOBOPTSEARCHPATH=,/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/jobOptions,/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/jobOptions,/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/InstallArea/jobOptions
DATAPATH=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/share:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/share:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/InstallArea/share:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/PartPropSvc/share
XMLPATH=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/InstallArea/XML:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/XML:/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a/InstallArea/XML
constituents= install_includes  HltTools TPathResolver config install_includes 
CMTINSTALLAREA=/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(BesPolicy_root)/cmt/requirements $(BesCxxPolicy_root)/cmt/requirements $(GaudiInterface_root)/cmt/requirements $(GaudiSvc_root)/cmt/requirements $(GaudiKernel_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(BesFortranPolicy_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(xrootd_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements 
use_includes= $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/Boss/7.0.5/BesCxxPolicy/BesCxxPolicy-00-01-01" $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/include" $(ppcmd)"/afs/.ihep.ac.cn/bes3/offline/ExternalLib/SLC6/ExternalLib/external/Boost/1.50.0_python2.7/x86_64-slc6-gcc46-opt/include/boost-1_50" $(ppcmd)"$(BesFortranPolicy_root)/src" $(ppcmd)"$(LCG_Platforms_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(HltTools_stamps)  $(BesPolicy_stamps)  $(BesCxxPolicy_stamps)  $(GaudiInterface_stamps)  $(GaudiSvc_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(Boost_stamps)  $(BesFortranPolicy_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps)  $(LCG_Platforms_stamps) 
use_cflags=  $(HltTools_cflags)  $(BesPolicy_cflags)  $(BesCxxPolicy_cflags)  $(GaudiInterface_cflags)  $(GaudiSvc_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(Boost_cflags)  $(BesFortranPolicy_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags)  $(LCG_Platforms_cflags) 
use_pp_cflags=  $(HltTools_pp_cflags)  $(BesPolicy_pp_cflags)  $(BesCxxPolicy_pp_cflags)  $(GaudiInterface_pp_cflags)  $(GaudiSvc_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(Boost_pp_cflags)  $(BesFortranPolicy_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(LCG_Platforms_pp_cflags) 
use_cppflags=  $(HltTools_cppflags)  $(BesPolicy_cppflags)  $(BesCxxPolicy_cppflags)  $(GaudiInterface_cppflags)  $(GaudiSvc_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(Boost_cppflags)  $(BesFortranPolicy_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags)  $(LCG_Platforms_cppflags) 
use_pp_cppflags=  $(HltTools_pp_cppflags)  $(BesPolicy_pp_cppflags)  $(BesCxxPolicy_pp_cppflags)  $(GaudiInterface_pp_cppflags)  $(GaudiSvc_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(Boost_pp_cppflags)  $(BesFortranPolicy_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(LCG_Platforms_pp_cppflags) 
use_fflags=  $(HltTools_fflags)  $(BesPolicy_fflags)  $(BesCxxPolicy_fflags)  $(GaudiInterface_fflags)  $(GaudiSvc_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(Boost_fflags)  $(BesFortranPolicy_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags)  $(LCG_Platforms_fflags) 
use_pp_fflags=  $(HltTools_pp_fflags)  $(BesPolicy_pp_fflags)  $(BesCxxPolicy_pp_fflags)  $(GaudiInterface_pp_fflags)  $(GaudiSvc_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(Boost_pp_fflags)  $(BesFortranPolicy_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(LCG_Platforms_pp_fflags) 
use_libraries= $(BesPolicy_libraries)  $(BesCxxPolicy_libraries)  $(GaudiInterface_libraries)  $(GaudiSvc_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Boost_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(BesFortranPolicy_libraries)  $(GCCXML_libraries)  $(xrootd_libraries)  $(CLHEP_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(LCG_Platforms_libraries) 
HltTools_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
HltTools_use_linkopts=  $(HltTools_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
TPathResolver_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TPathResolver_use_linkopts=  $(HltTools_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts) 
config_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_constituents= $(constituents)
constituentsclean= install_includesclean configclean TPathResolverclean HltToolsclean 
all_constituentsclean= $(constituentsclean)
